# Generated by Django 5.2.3 on 2025-07-24 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='parking.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo_vaga', models.CharField(choices=[('rua_coberta', 'Rua (Coberta)'), ('rua_descoberta', 'Rua (Descoberta)'), ('garagem', 'Garagem'), ('predio_coberta', 'Prédio (Coberta)'), ('predio_descoberta', 'Prédio (Descoberta)')], max_length=20)),
                ('has_camera', models.BooleanField(default=False)),
                ('size', models.CharField(default='Médio', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Ativa', max_length=20)),
                ('quantity', models.IntegerField(default=1, help_text='Número total de vagas neste local.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_availabilities', to='parking.parkingspot')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='parking.parkingspot')),
            ],
            options={
                'ordering': ['weekday', 'start'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpotPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parking_spot_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='parking.parkingspot')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, default='fotos_perfil/anonimo.jpg', null=True, upload_to='fotos_perfil/')),
                ('telefone', models.CharField(max_length=20)),
                ('modelo_veiculo', models.CharField(max_length=100)),
                ('marca_veiculo', models.CharField(max_length=100)),
                ('cor_veiculo', models.CharField(max_length=30)),
                ('placa_veiculo', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.parkingspot')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.reservation'),
        ),
        migrations.CreateModel(
            name='SpotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_quantity', models.IntegerField(default=1, help_text='Número de vagas disponíveis neste período da data.')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities_by_date', to='parking.parkingspot')),
            ],
            options={
                'ordering': ['available_date', 'start_time'],
                'unique_together': {('spot', 'available_date', 'start_time', 'end_time')},
            },
        ),
    ]
