# Generated by Django 5.2.3 on 2025-07-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='daily_end_time',
            field=models.TimeField(blank=True, help_text='Horário de término da diária (ex: 22:00)', null=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='daily_start_time',
            field=models.TimeField(blank=True, help_text='Horário de início da diária (ex: 10:00)', null=True),
        ),
    ]
