# Generated by Django 5.2.3 on 2025-08-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingspot_daily_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spotavailability',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='daily_end_time',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='daily_start_time',
        ),
        migrations.AddField(
            model_name='spotavailability',
            name='slot_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='spotavailability',
            unique_together={('spot', 'slot_number', 'available_date', 'start_time', 'end_time')},
        ),
    ]
