# Generated by Django 5.2.3 on 2025-07-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parkingspot_owner_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='marca_veiculo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='modelo_veiculo',
            field=models.CharField(max_length=100),
        ),
    ]
