# Generated by Django 5.2.3 on 2025-08-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_spotavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotavailability',
            name='slot_number',
            field=models.IntegerField(default=1, help_text='Número específico da vaga.'),
        ),
    ]
