# Generated by Django 5.2.3 on 2025-08-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_spotavailability_slot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slot_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
