# Generated by Django 5.2.3 on 2025-07-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_perfil_marca_veiculo_alter_perfil_modelo_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='fotos_perfil/anonimo.jpg', null=True, upload_to='fotos_perfil/'),
        ),
    ]
