# Generated by Django 5.2.3 on 2025-07-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkingspot_status_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='status',
            field=models.CharField(default='Ativa', max_length=20),
        ),
    ]
