# Generated by Django 5.2.3 on 2025-11-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_reservation_slot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('refused', 'Recusada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
