# Generated by Django 5.2.3 on 2025-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_parkingspot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='covered',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='tipo_vaga',
            field=models.CharField(choices=[('rua_coberta', 'Rua (Coberta)'), ('rua_descoberta', 'Rua (Descoberta)'), ('garagem', 'Garagem'), ('predio_coberta', 'Prédio (Coberta)'), ('predio_descoberta', 'Prédio (Descoberta)')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
