# Generated by Django 5.2.3 on 2025-07-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_remove_parkingspot_covered_parkingspot_tipo_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpotPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parking_spot_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='parking.parkingspot')),
            ],
        ),
    ]
