# Generated by Django 5.2.3 on 2025-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_parkingspotphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='num_vagas',
            field=models.IntegerField(default=1),
        ),
    ]
