# Generated by Django 5.2.3 on 2025-07-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_parkingspot_num_vagas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='num_vagas',
        ),
    ]
